name: Update and Deploy Classement

on:
  schedule:
    - cron: "*/15 * * * *" # toutes les 15 minutes
  workflow_dispatch:       # déclenchement manuel

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jinja2 pytz selenium
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run script
        run: python main.py

      - name: Upload artifact (HTML files)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs   # on envoie le dossier docs/ pour Pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
