name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Installer Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium pandas pytz

    # Installer Chromium et Chromedriver
    - name: Install Chromium & Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        chromium-browser --version
        chromedriver --version

    # Lancer le script Python
    - name: Run main.py
      run: python main.py
